dist: trusty
sudo: false
language: java
jdk:
- oraclejdk8
branches:
  except:
  - /\+travis\d+$/
env:
  global:
  - MAVEN_BASE_URL=https://atomist.jfrog.io/atomist
  - secure: dLEec5bFacbZlu0gMdyi+XZ+mh72JRsiYpbSc3QJHWiBH6EXv9ZetTS59KY2quWjTeApC4AY7qTOn6D1CEa5VWsJFfdymspu3i/aDIQ954SFydUgUhHTDzE/IsqcTmAa6KJki5q7hxNM8s3A2KFaiNlKEZJDoQi2F+WFA16LK+0wVSlPyXoyQuEtkBi9umxXGXzPit0EVRL9WUyQXdOZpdkhNa513fFEjE7RFhjBauipMcI0q2Dxrhg8dLztkz5TZfstTfpFcW7IELUN42b9OVyVjLYtf2/b6P9z1ZXXHPJrV04XZ6RAblxbeqyLm961hltsCr9vznyzFWksVGCUYOamFB9SrPsIxte4Tz1HhNs+VFX7T22dzUOMF10lAd4+PFhOLnoetVuSpZQFzGoh6Ev3L1RDOIozezLT8tpo8lEYR9dyY1sXmoBiBZsiMy/sCmpMjwun0s4oQyhE6rGiwT2l/NwNZ8KxxpN6Fx9LGbM7SsRCACf8qKdzlUNonZvMNsuxHxq4oClJa5D/32gjDLvCAjgFS1K3p29+Jf7FQ2Q0pmoTa0EvqvDlRjwIUtCh0rSL/VxShJv5UgqTWm1KVd/F7wXRIQTT4wbJnt/7/UBxZKFkI6xcLwMz8WomapzmGAXXxeKGuwQkj6ca7urmwGKMjUN1VNo3R5fvkxCOH2Q=
  - secure: tbe6PJfY4B3fP6mKL0lGfwdtUtH8HSyhJcWKnqYVfSnkv43LRz70aNuQu+URUYGT29t4a3ZffmFjRKo+P3ZJf4YXvMQuzkGBsb83CMM55cvNHcSXd3jKmzP3pPlMrvJXA0SmXY71JIBc3H1xbLHQ5oFwvEExJlfn2T+MEdhVLM6fNeCHXJKB950y1WNa1juls2hm3uwBcZ1XKH+VBnfMOISViODhZhFlghKeULSAxm7N4x+Bjq/tPfZ0b4t90Qd7gUgen1s9fii8HjKPpO2P2f7JKpdZgYS9d3N4sRdslLtivw9w4FlVGBTP0R+8gR9C/O2N+6JfCJIbz4NMu4AwveLR9cZG+qho+urN/YJYcVzwKuMVuLTppHejTGeR1F3eVcykhgJKl6LXF52GI7Vq85jcRw2pXkZPruLhYbfpDz69+Mg7i2x3bewW5cSKQMmQbWgXYVA+xRrRdt1zf6/6Rx0P/XqvprAGhiy5Np6E7Obb0wWGcCJrQd0eY9/UBgUX+h+z+vXyHh8q9w+h8fSWky6Ey+KeTKcBXalfezhAodyhAJxGtaHu+T5Y95hfbeisnyvEoP/J65eS/xtc2sxjqRRjLyvbsMMypW4qrFRGaemqFd78vcEhv5XaRKA1NHyECjRJUieeU2073nId1sOC0AwB9aAGtsHdszycuJN35uY=
  - secure: yGabpaTiphtqletMmoYWITq05lRNoUt5P/G5BOFaVmt2nV6JH2KyrUuf2ToQVkYVop1t8qhWBVm935hKBU6AUs9hi3Wjg6Kuy45CF/Nk211fZ9g2aKnGGiR+fMaxAdP36ekHl1xwp6wZf19oNXWd3lwI8cO8LE6W+VMOboI+4iHULLnYoNNn57yZF5pdMHNb4ziyCOh9yDXDLJIwyhiV4KkGtUMNkTHO2mbIy+PEqi7us9mizuTBe3qc4TX/k2+GUwOFsD4z5xF4MoYoF1NDEIiUF4RvUUcUa1HdgCobfN4nSEInz/Q1o6S3DlMabfmpo1dpmwg0l1HeOiDrIZxUWGIuUTD/KH/lzLEYxqmM0I+LRkIyOxNvkTWIF8flTHDbztVQglXPBoEubnJ2aPnq18zsCcvlGJ2a9rnRVeby06NOKTYVjGf0HmIdFYKVNXFblhNHIvPiHW0MCZS55fEgCGzuBv/USyHfaR45Q1cHNXpMQgiH0kL2WyNSk73TlvXjTcc9lpjoEA0qMVaGZwCIfesLDz1mUEbX3ma7EQpsuJyhAC8HOIxo+K3iBgfbSBiDr/Tjyhl1vJZvXShVIXNGrRR7TOk83feLtJ/wWBsvqw9EdQUZhHb2Gqszguhk57vBa8pxyMJCU6vVp66UjNWuHu1OP0LCKjut4NWipBIBo0Y=
install:
- nvm install 6.9.2
script: bash .atomist/build/travis-build.bash
notifications:
  email: false
  webhooks:
    urls:
    - https://webhook.atomist.com/travis
    on_success: always
    on_failure: always
    on_start: always
cache:
  directories:
  - $HOME/.atomist
